name: LTS
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"
  push:
    branches:
      - trunk
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight UTC

jobs:
  build:
    uses: ./.github/workflows/build.yml

  lts:
    name: Tests (LTS)
    uses: ./.github/workflows/tests.yml
    with:
      runtime: lts
    secrets: inherit

  # Will be removed in the future
  plugins-tests:
    name: Plugins Tests

    uses: ./.github/workflows/plugins-tests.yml
    with:
      registry: docker.eventstore.com/eventstore-ee
      image: eventstoredb-commercial
      tag: 24.2.0-jammy
    secrets: inherit
