name: Previous LTS
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"
  push:
    branches:
      - trunk
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight UTC

jobs:
  build:
    uses: ./.github/workflows/build.yml

  previous-lts:
    name: Tests (Previous LTS)
    uses: ./.github/workflows/tests.yml
    with:
      runtime: previous-lts
    secrets: inherit
